#!/bin/sh
set -eu

[ -r $PWD/$0 ] &&
  dir=$(dirname $PWD/$0) ||
  dir=$(dirname $0)

link() { rm -rf $HOME/.$1; ln -vs $dir/$1 $HOME/.$1; }
copy() { rm -rf $HOME/.$1; cp -vp $dir/$1 $HOME/.$1; }

# ssh,gdb hate symlinks
cp -v $dir/ssh_config   $HOME/.ssh/config
chmod 644 $HOME/.ssh/config
copy gdbinit

# these guys are fine with symlinks
[ $(uname) == "Darwin" ] || link xinitrc
link bashrc
link bash_profile
link screenrc
link emacs
link elisp
link eshell
link gitconfig
link vimrc
