#!/bin/sh
# git clone git://github.com/jgmalcolm/config.git && cd config && ./update
set -eu

[ -r $PWD/$0 ] &&
  dir=$(dirname $PWD/$0) ||
  dir=$(dirname $0)

link() { rm -rf ~/.$1; ln -vs $dir/$1 ~/.$1; }
copy() { rm -rf ~/.$1; cp -vp $dir/$1 ~/.$1; chmod go-w ~/.$1; }

# ssh,gdb hate symlinks
cp -v $dir/ssh_config   ~/.ssh/config
chmod 644 ~/.ssh/config
copy gdbinit

# these guys are fine with symlinks
[ $(uname) == "Darwin" ] || link xinitrc
link bashrc
link bash_profile
link screenrc
link emacs
link elisp
link eshell
link vimrc
link xpdfrc
link input
link gitconfig
link git-prompt.sh
link git-completion.sh
link bin
